version: "2.1"
services:
  validator-3:
    image: hyperledger/sawtooth-validator:1.0
    container_name: validator-3
    expose:
      - 4004
      - 8800
    volumes:
      - ./settings:/settings
    entrypoint: "bash -c \"\
      cp /settings/validator.toml /etc/sawtooth/validator.toml && \
      sawadm keygen && \
      sawtooth-validator -vv \
    \""
    networks:
      - sawtooth

  settings-tp-3:
    image: hyperledger/sawtooth-settings-tp:1.0
    container_name: settings-tp-3
    depends_on:
      - validator-3
    entrypoint: settings-tp -vv -C tcp://validator-3:4004
    networks:
      - sawtooth

  poet-registry-tp-3:
    image: hyperledger/sawtooth-poet-validator-registry-tp:1.0
    container_name: poet-registry-tp-3
    expose:
      - 4004
    command: poet-validator-registry-tp -C tcp://validator-3:4004
    networks:
      - sawtooth

  rest-api-3:
    image: hyperledger/sawtooth-rest-api:1.0
    container_name: rest-api-3
    expose:
      - 8008
    entrypoint: sawtooth-rest-api -C tcp://validator-3:4004 --bind rest-api-3:8008
    depends_on:
      - validator-3
    networks:
      - sawtooth

networks:
  sawtooth:
    external:
      name: sawtooth
