version: "2.1"
services:
  validator-1:
    image: hyperledger/sawtooth-validator:1.0
    container_name: validator-1
    expose:
      - 4004
      - 8800
    volumes:
      - ./settings:/settings
    entrypoint: "bash -c \"\
      cp /settings/validator.toml /etc/sawtooth/validator.toml && \
      sawadm keygen && \
      sawtooth-validator -vv \
    \""
    networks:
      - sawtooth

  settings-tp-1:
    image: hyperledger/sawtooth-settings-tp:1.0
    container_name: settings-tp-1
    depends_on:
      - validator-1
    entrypoint: settings-tp -vv -C tcp://validator-1:4004
    networks:
     - sawtooth

  poet-registry-tp-1:
    image: hyperledger/sawtooth-poet-validator-registry-tp:1.0
    container_name: poet-registry-tp-1
    expose:
      - 4004
    command: poet-validator-registry-tp -C tcp://validator-1:4004
    networks:
      - sawtooth

  rest-api-1:
    image: hyperledger/sawtooth-rest-api:1.0
    container_name: rest-api-1
    expose:
      - 8008
    entrypoint: sawtooth-rest-api -C tcp://validator-1:4004 --bind rest-api-1:8008
    depends_on:
      - validator-1
    networks:
      - sawtooth

networks:
  sawtooth:
    external:
      name: sawtooth
